version: '2.3'
services:
  training:
    image: 172.20.40.190:5000/tf-2.3.0-gpu:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=4,5,6,7
    user: "2004:2004"
    container_name: "moono_gpu_4567"
    volumes:
      - "/mnt/vision-nas/moono/git-repos/moco-tf2.x:/work-dir"
      - "/mnt/vision-nas/moono/trained_models/moco-tf-2.x:/model-dir"
#      - "/mnt/vision-nas/moono/moco-official-converted/moco_v2_800ep:/pretrained-model-dir:ro"
      - "/mnt/vision-nas/data-sets/tensorflow_datasets:/tfds-dir:ro"
    working_dir: "/work-dir"
    command: ["python", "-u", "train.py",
              "--allow_memory_growth", "false",
              "--debug_split_gpu", "false",
              "--use_tf_function", "true",
              "--name", "trial_5_gpu_4",
              "--tfds_data_dir", "/tfds-dir",
              "--model_base_dir", "/model-dir",
              "--moco_version", "1",
              "--aug_op", "GPU",
              "--batch_size_per_replica", "64",
              "--epochs", "200",
              "--initial_lr", "0.03",
    ]
  watching:
    image: 172.20.40.190:5000/tf-2.3.0-gpu:latest
    user: "2004:2004"
    container_name: "moono_tensorboard"
    depends_on:
      - training
    volumes:
      - "/mnt/vision-nas/moono/trained_models/moco-tf-2.x:/model-dir"
    ports:
      - "36006:6006"
    working_dir: "/model-dir"
    command: ["tensorboard", "--logdir", "./", "--host", "0.0.0.0", "--port", "6006"]
