version: '2.3'
services:
  training:
    image: 172.20.40.190:5000/tf-2.0.0-gpu-py3:tfds
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=2,3
    user: "2004:2004"
    container_name: "moono_gpu_23"
    volumes:
      - "/mnt/vision-nas/moono/git-repos/moco-tf2.x:/work-dir"
      - "/mnt/vision-nas/moono/trained_models/moco-tf-2.x:/model-dir"
      - "/mnt/vision-nas/moono/moco-official-converted/moco_v2_800ep:/pretrained-model-dir:ro"
      - "/mnt/vision-nas/data-sets/tensorflow_datasets:/tfds-dir:ro"
    working_dir: "/work-dir"
    command: ["python", "-u", "linear_classification_protocol.py",
              "--allow_memory_growth", "false",
              "--debug_split_gpu", "false",
              "--use_tf_function", "true",
              "--name", "trial1",
              "--tfds_data_dir", "/tfds-dir",
              "--model_base_dir", "/model-dir",
              "--pretrained_ckpt", "/pretrained-model-dir/ckpt-0",
              "--pretrained_moco_version", "2",
              "--batch_size_per_replica", "128",
              "--initial_lr", "30.0",
    ]
  watching:
    image: 172.20.40.190:5000/tf-2.0.0-gpu-py3:tfds
    user: "2004:2004"
    container_name: "moono_tensorboard"
    depends_on:
      - training
    volumes:
      - "/mnt/vision-nas/moono/trained_models/moco-tf-2.x:/model-dir"
    ports:
      - "36006:6006"
    working_dir: "/model-dir"
    command: ["tensorboard", "--logdir", "./", "--host", "0.0.0.0", "--port", "6006"]
